version: 0.0
os: linux
files:
  - source: /src
    destination: /opt/source/Backend/
  - source: /pom.xml
    destination: /opt/source/Backend/
    
permissions:
  - object: /opt/
    owner: ec2-user
    mode: 777
    type:
    - directory
    
hooks:
  AfterInstall:
    - location: scripts/build_script
      timeout: 300
      runas: ec2-user
      
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user

