version: 0.0
os: linux
files:
  - source: /src
    destination: /opt/source/Backend
  - source: /pom.xml
    destination: /opt/source
  - source: /Backend.war
    destination: /opt/tomcat8/webapps/
    
permissions:
  - object: /opt/
    owner: ec2-user
    mode: 777
    type:
    - directory
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user

